Tests: update patch to use the ipv4's 127.0.0.1 instead of localhost to also patch the ipp:// shared printer URL, that fixes the tests

diff --git a/debian/patches/tests-use-ipv4-lo-address.patch b/debian/patches/tests-use-ipv4-lo-address.patch
--- a/debian/patches/tests-use-ipv4-lo-address.patch
+++ b/debian/patches/tests-use-ipv4-lo-address.patch
@@ -1,7 +1,9 @@
-Description: Use 127.0.0.1 instead of localhost in the test-suite. This should make the test-suite work in pbuilder.
+Description: Use 127.0.0.1 instead of localhost in the test-suite. This should
+ make the test-suite work in pbuilder. It apparently also fixes an ipp backend
+ problem in the test-suite.
 Author: Didier Raboud <odyx@debian.org>
 Origin: vendor
-Last-Update: 2015-08-06
+Last-Update: 2016-08-05
 
 --- a/test/run-stp-tests.sh
 +++ b/test/run-stp-tests.sh
@@ -36,3 +38,16 @@ Last-Update: 2015-08-06
  		options=""
  	fi
  	$VALGRIND ./ipptool -tI $options $uri $file >> $strfile
+--- a/test/5.1-lpadmin.sh
++++ b/test/5.1-lpadmin.sh
+@@ -55,8 +55,8 @@
+ 
+ echo "Add Shared Printer Test"
+ echo ""
+-echo "    lpadmin -p Test3 -E -v ipp://localhost:$IPP_PORT/printers/Test2 -m raw"
+-$VALGRIND ../systemv/lpadmin -p Test3 -E -v ipp://localhost:$IPP_PORT/printers/Test2 -m raw 2>&1
++echo "    lpadmin -p Test3 -E -v ipp://127.0.0.1:$IPP_PORT/printers/Test2 -m raw"
++$VALGRIND ../systemv/lpadmin -p Test3 -E -v ipp://127.0.0.1:$IPP_PORT/printers/Test2 -m raw 2>&1
+ if test $? != 0; then
+ 	echo "    FAILED"
+ 	exit 1
